os: windows
language: node_js
node_js:
  - lts/*
script: node ygopro-server.js
before_install:
  - npm i -g npm@12
cache:
  npm: false
git:
  depth: false
  quiet: true
  clone: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  committer_from_gh: true
branches:
  only:
    - master
