dist: bionic 
language: node_js
node_js:
  - lts/*
script:
  - sudo firewall-cmd --zone=public --permanent --add-port=7999/tcp
  - sudo firewall-cmd --zone=public --permanent --add-port=7922/tcp
  - sudo firewall-cmd --zone=public --permanent --add-port=22/tcp
  - sudo firewall-cmd --reload
  - node ygopro-server.js
cache:
  npm: false
git:
  depth: false
  quiet: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  committer_from_gh: true
branches:
  only:
    - master
